### PR TITLE
fix: initial implementation of mouse tracking disabling after exit

### LINKED ISSUE #14: Mouse tracking not disabled after exiting waha-tui
I noticed right after exiting waha-tui on both version with bunx & `bun run dev`, the terminal will spew out these characters like so whenever I move my mouse.  

Image

I need to run `tput reset` to stop this behaviour.

Terminal Emulator: Windows Terminal
Operating System: WSL (Ubuntu 22.04.5 LTS)

### PR DESCRIPTION
**Pull request by opariffazman**
Simple fix for the mouse tracking issue, tested and worked on my end.

Should close #14 if nothing else breaks. Thanks!

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -152,16 +152,55 @@ async function main() {
...
+      stopPresenceManagement()
+
+      // Disconnect WebSocket
+      webSocketService.disconnect()
+
+      // Destroy renderer to restore terminal state (disables mouse tracking, restores cursor, etc.)
+      if (renderer && typeof renderer.destroy === "function") {
+        renderer.destroy()
+      }
+    } catch (error) {
```
Comment (muhammedaksam) [inline src/index.ts]: I am going to add this after merging to develop.

```ts
      debugLog("App", `Cleanup error: ${error}`)
```

**Review by muhammedaksam — APPROVED** [review]
Thank you for the PR!
